#!/bin/bash
################## CHANGE ME ########################
USER="root" #SERVER user goes here - if not root
REMOTE="rdm" #SERVER IP goes here
REMOTE_PATH="/home/weston/webapps/egen" #PATH on REMOTE SERVER
REMOTE2="$REMOTE"
REMOTE_PATH2="$REMOTE_PATH"
####################################################

COLOR='\033[0;32m' #green
NC='\033[0m' #no-color
MALFUNCTION="👨‍🚀 Huston, We have a problem! Make sure all your parameters are correct"
OOPS="🚀💥🔥 OOPS! Try using ${COLOR}ready${NC} or ${COLOR}ready go${NC}"

if [ $# -eq 0 ]
  then
    echo "$MALFUNCTION"
elif [ "$1" == "ready" ]
  then
    if [[ -z "$2" ]]
      then
        echo "Running prelaunch ✅ check to 🪐 $REMOTE..."
        rsync --dry-run -az --force --delete --progress --exclude-from=misfits.txt -e "ssh -p22" ./ "$USER"@"$REMOTE":"$REMOTE_PATH"
    elif [ "$2" == "go" ]
      then
        echo "And we have 🚀 Liftoff to 🪐 - $REMOTE2..."
        rsync -az --force --delete --progress --exclude-from=misfits.txt -e "ssh -p22" ./ "$USER"@"$REMOTE2":"$REMOTE_PATH2"
    else
      echo "$MALFUNCTION"
    fi
  else
    echo -e "$OOPS"
fi
